import re
patterns = {
    'GSTIN': r'[Gg][Ss][Tt][Ii][Nn]\s*[:\|\-\s]*\s*(\w+)',
    'Invoice Number': r'[Ii]nvoice\s*[Nn]o[\.\s]*\s*[:\|\-\s]*\s*(\w+)',
    'Invoice Date': r'[Ii]nvoice\s*[Dd]ate[\[\]\:\s]*\s*(\d+\s*[A-Za-z]+\s*\d{4})',
    'Date of Supply': r'[Dd]ate\s*[Oo]f\s*[Ss]upply[\[\]\:\s]*\s*(\d+\s*[A-Za-z]+\s*\d{4})',
    'State': r'[Ss]tate[\:\|\s]*([\w\s]+)',
    'State Code': r'[Cc]ode[\:\|\s]*\s*(\d+)',
    'Place of Supply': r'[Pp]lace\s*[Oo]f\s*[Ss]upply[\:\|\s_]*([\w\s,]+)',
    'Bill To': r'[Bb]ill\s*[Tt]o[\:\s]*([\w\s\.\,]+)',
    'Bill To Address': r'[Bb]ill\s*[Tt]o[\:\s]*([\w\s\.\,]+)[\s\[\|\-]*[Gg][Ss][Tt][Ii][Nn][\:\|\-\s]*\s*(\w+)',
    'Ship To': r'[Ss]hip\s*[Tt]o[\:\s]*([\w\s\.\,]+)',
    'Ship To Address': r'[Ss]hip\s*[Tt]o[\:\s]*([\w\s\.\,]+)[\s\[\|\-]*[Gg][Ss][Tt][Ii][Nn][\:\|\-\s]*\s*(\w+)',
    'Ship To GSTIN': r'[Gg][Ss][Tt][Ii][Nn]\s*[:\|\-\s]*\s*(\w+)',
    'Ship To State': r'[Ss]tate[\:\|\s]*([\w\s]+)',
    'Ship To State Code': r'[Cc]ode[\:\|\s]*\s*(\d+)',
    'Product Description': r'(\d+)\s*([\w\s,]+)\s*(\d+)\s*(\d+)\s*(\d+)\s*(\d+.\d+)\s*(\d+.\d+)',
    'Total Invoice Amount before Tax': r'[Tt]otal\s*[Aa]mount\s*[Bb]efore\s*[Tt]ax[\:\|\s]*\s*(\d+.\d+)',
    'Freight & Insurance': r"Freight & Insurance ‘([\d.]+)",
    'Total Invoice Amount after Tax': r"Total Amount after Tax: '([\d.]+)",
    'Payment Term': r"Payment Term\s*([\s\S]*?)\n",
    'Terms & Conditions': r"Terms & conditions\s*([\s\S]*?)\n\n",
    'Authorised Signatory': r"Authorised signatory\s*([\s\S]*)",
    'company_address_pattern' : r'^([\w\s,.-]+)\nTel',
    'phone_pattern' : r'Tel\s:\s([\d-]+)\n',
    'website_pattern' : r'Web\s:\s([\w.:/]+)\s',
    'email_pattern' : r'Email\s:\s([\w@.]+)\n',
    'gstin_pattern' : r'GSTIN\s:\s(\w+)\s',
    'invoice_number_pattern' : r'invoice No\s(\d+)',
    'invoice_date_pattern' : r'tavoice Date\s([0-9]{2}-[A-Za-z]{3}-[0-9]{4})',
    'customer_name_pattern' : r'^([A-Z\s.]+)Chall',
    'challan_number_pattern' : r'Chall No\.\s(\w+)',
    'challan_date_pattern' : r'Challan Date\s([0-9]{2}-[A-Za-z]{3}-[0-9]{4})',
    'customer_address_pattern' : r'Address\s([\w\s,.:-]+)PHONE',
    'customer_phone_pattern' : r'PHONE\s([\d-]+)\n',
    'lr_number_pattern' : r'LR\.No\.\s([\w\s]+)\Due',
    'due_date_pattern' : r'Due Date\s([0-9]{2}-[A-Za-z]{3}-[0-9]{4})',
    'transporter_pattern' : r'Transport\s([\w\s]+)\nBeco',
    'vehicle_type_pattern' : r'Vehicle\sType\s([\w\s]+)\sVehicle',
    'vehicle_number_pattern' : r'Vehicle\sNumber\s(\w+)\n',
    'shipping_bill_number_pattern' : r'Ship\.\sBill\sno:\s(\d+)\s',
    'shipping_bill_date_pattern' : r'Ship\.\sBill\sdate\s([0-9]{2}-[A-Za-z]{3}-[0-9]{4})\s',
    'shipping_port_code_pattern' : r'Ship\.\sPort\scode\s(\w+)\n',
    'pre_carriage_by_pattern' : r'Pre-carriage\sby\s([\w\s]+)\sPlace',
    'port_of_loading_pattern' : r'Port\sof\sLoading\s([\w\s,]+)\sPort',
    'port_of_discharge_pattern' : r'Port\sof\sDischarge\s([\w\s,]+)\nFinal',
    'final_destination_pattern' : r'Final\sDestiantion\s([\w\s,.:-]+)\nCountry',
    'country_of_origin_pattern' : r'Country\sof\sOrigin\s([A-Za-z\s]+)\sCountry',
    'country_of_final_pattern' : r'Country\sof\sFinal\s([A-Za-z\s]+)',
    'product_name_pattern' : r'^\d+\.\s\[?([\w\s]+)\s*\|?\s*\d+\.\d+Pcs\s\d+\s\d+\.\d+\)\n',
    'total_amount_pattern' : r'TOTAL\sAMOUNT\sEUR\s(\d+\.\d{2})\n',
    'bank_name_pattern' : r'Bank\sName\s([\w\s]+)\nBranch',
    'branch_name_pattern' : r'Branch\sName\s([\w\s]+)\nBank',
    'bank_account_number_pattern' : r'Bank\sAccount\sNumber\s(\d+)\n',
    'bank_swift_code_pattern' : r'Bank\sSwift\sCode\s(\w+)\n',
}
